server:
  listen: 8080
  workers: 4
  upstreams:
    - id: node1
      url: http://localhost:8000

    - id: node2
      url: http://localhost:8001
  headers:
    - key: Authorization
      value: "Bearer xyz"
  rules:
    - path: /
      upstreams:
        - node1
        - node2

    - path: /admin
      upstreams:
        - node2
