server:
  listen: 8080
  workers: 4
  upstreams:
    - id: jsonplaceholder
      url: jsonplaceholder.typicode.com

    - id: dummyjson
      url: dummyjson.com
  headers:
    - key: Authorization
      value: "Bearer xyz"
  rules:
    - path: /test
      upstreams:
        - dummyjson

    - path: /
      upstreams:
        - jsonplaceholder
